### ISSUE TITLE
Text in den Flyern ist kein Textobjekt

### ISSUE THREAD

**Issue by funkenstrahlen** [ffka/propaganda#2]
Ich wollte eben den Flyer Hallo Nachbar ein wenig anpassen. Alle Schriften installiert, mit Inkscape geöffnet.

Leider sind die Texte als Vektorobjekt und nicht als Textobjekt vorhanden. Der Text lässt sich also nicht einfach editieren.

**Comment by fuxii** [comment]
Ich habe die beiden SVGs gerade nochmals ausgecheckt und angeschaut: Sowohl die Vorder- als auch die Rückseite der "Hallo Nachbar"-Vorlagen sind vollständig editierbar.

Hast du evtl. die Pfad-Version erwischt?

**Comment by funkenstrahlen** [comment]
> Hast du evtl. die Pfad-Version erwischt?

Herrje... Ist wohl noch zu früh. /o\

Danke :)
